name: nta2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - numpy
  - scipy
  - matplotlib
  - tensorboard
  - tqdm
  - wheel
  - pytorch::pytorch
  - pytorch::pytorch-cuda=13.0
  - pip:
      - -r ../requirements-windows.txt
      - -e ..
